"""4

Revision ID: 1a8fa8835bb7
Revises: c98af2a51a5d
Create Date: 2025-06-13 00:30:27.372549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a8fa8835bb7'
down_revision: Union[str, None] = 'c98af2a51a5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('driver_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'cars', 'drivers', ['driver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.drop_column('cars', 'driver_id')
    # ### end Alembic commands ###
