"""Add user table

Revision ID: f2282b1c01aa
Revises: 
Create Date: 2025-06-11 20:45:29.642188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2282b1c01aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cars', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.create_index(op.f('ix_cars_id'), 'cars', ['id'], unique=False)
    op.drop_constraint(op.f('fk_user'), 'cars', type_='foreignkey')
    op.create_foreign_key(None, 'cars', 'users', ['user_id'], ['user_id'])
    op.alter_column('users', 'about',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'about',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user'), 'cars', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_cars_id'), table_name='cars')
    op.alter_column('cars', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
